### ISSUE TITLE
Switch to form/submit instead of button/click event?

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/giffaw#2]
Given that we introduce this lab after talking about forms it may make more sense to use a form instead of the current input/button setup.

**Comment by nathanallen** [comment]
Drawbacks:
- must capture `submit` event
- must use `preventDefault`

Pros:
- Means we can use `serialize`
- no "naked" input (input outside of a form)

**Comment by tgaff** [comment]
I'm ok with either.  The use of form does fit in better with the sequence, but if this turns out to be a big change we should hold-off; it's a little late.
